!SESSION 2017-08-08 14:20:43.456 -----------------------------------------------
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ko_KR
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:21:12.185
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.number'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:21:12.185
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.round'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:21:12.232
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.number'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:21:12.232
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.round'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:21:12.248
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.number'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:21:12.248
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.round'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:21:13.823
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.number'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:21:13.823
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.round'

!ENTRY org.eclipse.egit.ui 2 0 2017-08-08 14:21:19.959
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\user'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:22.465
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.beanshell.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:22.477
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.dbunit.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:22.478
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.derby.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:22.479
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.erd.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:22.479
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:22.480
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.flatfiles.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:22.492
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.help.feature_3.3.9.jar.
!SESSION 2017-08-08 14:22:47.832 -----------------------------------------------
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_131
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ko_KR
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product -data file:/C:/ncs03/python_work/ -product org.eclipse.epp.package.jee.product

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.495
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.beanshell.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.495
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.dbunit.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.511
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.derby.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.511
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.erd.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.511
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.511
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.flatfiles.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.511
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.help.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.636
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.beanshell.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.636
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.dbunit.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.636
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.derby.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.636
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.erd.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.636
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.636
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.flatfiles.feature_3.3.9.jar.

!ENTRY org.eclipse.equinox.p2.publisher.eclipse 4 0 2017-08-08 14:22:55.636
!MESSAGE Unable to acquire PluginConverter service during generation for: C:\ncs03\eclipse\features\com.quantum.help.feature_3.3.9.jar.

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:22:59.961
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.number'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:22:59.961
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.round'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:22:59.992
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.number'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:22:59.992
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.round'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:23:00.007
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.number'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:23:00.007
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.round'

!ENTRY org.eclipse.egit.ui 2 0 2017-08-08 14:23:02.175
!MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
user global configuration and to define the default location to store repositories: 'C:\Users\user'. If this is
not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
EGit might behave differently since they see different configuration options.
This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

!ENTRY org.python.pydev.shared_core 1 1 2017-08-08 14:23:59.939
!MESSAGE Information about process of adding new interpreter:
- Opening dialog to request executable (or jar).
- Chosen interpreter (name and file):'Tuple [C:\Python27\python.exe -- C:\Python27\python.exe]
- Ok, file is non-null. Getting info on:C:\Python27\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Python27\python.exe -u C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Python27\python.exe -u C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Python27\python.exe -u C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Success getting the info. Result:<xml>
<name>C:\Python27\python.exe</name>
<version>2.7</version>
<executable>C:\Python27\python.exe</executable>
<lib>C:\Python27\DLLs</lib>
<lib>C:\Python27\lib</lib>
<lib>C:\Python27\lib\lib-tk</lib>
<lib>C:\Python27</lib>
<lib>C:\Python27\lib\site-packages</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>__builtin__</forced_lib>
<forced_lib>__main__</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>gi</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>mock</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>multiprocessing</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>six</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>ssl</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
</xml>

!STACK 0
java.lang.RuntimeException: Information about process of adding new interpreter:
- Opening dialog to request executable (or jar).
- Chosen interpreter (name and file):'Tuple [C:\Python27\python.exe -- C:\Python27\python.exe]
- Ok, file is non-null. Getting info on:C:\Python27\python.exe
- Beggining task:Getting libs totalWork:100
- Setting task name:Mounting executable string...
- Setting task name:Executing:  C:\Python27\python.exe -u C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\interpreterInfo.py
- Setting task name:Making pythonpath environment... C:\Python27\python.exe -u C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\interpreterInfo.py
- Setting task name:Making exec... C:\Python27\python.exe -u C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\interpreterInfo.py
- Setting task name:Reading output...
- Setting task name:Waiting for process to finish.
- Success getting the info. Result:<xml>
<name>C:\Python27\python.exe</name>
<version>2.7</version>
<executable>C:\Python27\python.exe</executable>
<lib>C:\Python27\DLLs</lib>
<lib>C:\Python27\lib</lib>
<lib>C:\Python27\lib\lib-tk</lib>
<lib>C:\Python27</lib>
<lib>C:\Python27\lib\site-packages</lib>
<forced_lib>Image</forced_lib>
<forced_lib>OpenGL</forced_lib>
<forced_lib>__builtin__</forced_lib>
<forced_lib>__main__</forced_lib>
<forced_lib>_ast</forced_lib>
<forced_lib>_bisect</forced_lib>
<forced_lib>_bytesio</forced_lib>
<forced_lib>_codecs</forced_lib>
<forced_lib>_codecs_cn</forced_lib>
<forced_lib>_codecs_hk</forced_lib>
<forced_lib>_codecs_iso2022</forced_lib>
<forced_lib>_codecs_jp</forced_lib>
<forced_lib>_codecs_kr</forced_lib>
<forced_lib>_codecs_tw</forced_lib>
<forced_lib>_collections</forced_lib>
<forced_lib>_csv</forced_lib>
<forced_lib>_fileio</forced_lib>
<forced_lib>_functools</forced_lib>
<forced_lib>_heapq</forced_lib>
<forced_lib>_hotshot</forced_lib>
<forced_lib>_io</forced_lib>
<forced_lib>_json</forced_lib>
<forced_lib>_locale</forced_lib>
<forced_lib>_lsprof</forced_lib>
<forced_lib>_md5</forced_lib>
<forced_lib>_multibytecodec</forced_lib>
<forced_lib>_random</forced_lib>
<forced_lib>_sha</forced_lib>
<forced_lib>_sha256</forced_lib>
<forced_lib>_sha512</forced_lib>
<forced_lib>_sre</forced_lib>
<forced_lib>_struct</forced_lib>
<forced_lib>_subprocess</forced_lib>
<forced_lib>_symtable</forced_lib>
<forced_lib>_warnings</forced_lib>
<forced_lib>_weakref</forced_lib>
<forced_lib>_winreg</forced_lib>
<forced_lib>array</forced_lib>
<forced_lib>audioop</forced_lib>
<forced_lib>binascii</forced_lib>
<forced_lib>cPickle</forced_lib>
<forced_lib>cStringIO</forced_lib>
<forced_lib>cmath</forced_lib>
<forced_lib>datetime</forced_lib>
<forced_lib>email</forced_lib>
<forced_lib>errno</forced_lib>
<forced_lib>exceptions</forced_lib>
<forced_lib>future_builtins</forced_lib>
<forced_lib>gc</forced_lib>
<forced_lib>gi</forced_lib>
<forced_lib>hashlib</forced_lib>
<forced_lib>imageop</forced_lib>
<forced_lib>imp</forced_lib>
<forced_lib>itertools</forced_lib>
<forced_lib>marshal</forced_lib>
<forced_lib>math</forced_lib>
<forced_lib>mmap</forced_lib>
<forced_lib>mock</forced_lib>
<forced_lib>msvcrt</forced_lib>
<forced_lib>multiprocessing</forced_lib>
<forced_lib>nt</forced_lib>
<forced_lib>numpy</forced_lib>
<forced_lib>operator</forced_lib>
<forced_lib>os</forced_lib>
<forced_lib>os.path</forced_lib>
<forced_lib>parser</forced_lib>
<forced_lib>pytest</forced_lib>
<forced_lib>scipy</forced_lib>
<forced_lib>signal</forced_lib>
<forced_lib>six</forced_lib>
<forced_lib>socket</forced_lib>
<forced_lib>ssl</forced_lib>
<forced_lib>strop</forced_lib>
<forced_lib>sys</forced_lib>
<forced_lib>thread</forced_lib>
<forced_lib>time</forced_lib>
<forced_lib>wx</forced_lib>
<forced_lib>wxPython</forced_lib>
<forced_lib>xxsubtype</forced_lib>
<forced_lib>zipimport</forced_lib>
<forced_lib>zlib</forced_lib>
</xml>

	at org.python.pydev.core.log.Log.logInfo(Log.java:66)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterEditor.getNewInputObject(AbstractInterpreterEditor.java:990)
	at org.python.copiedfromeclipsesrc.PythonListEditor.addPressed(PythonListEditor.java:132)
	at org.python.copiedfromeclipsesrc.PythonListEditor$1.widgetSelected(PythonListEditor.java:225)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.ui.internal.dialogs.WorkbenchPreferenceDialog.open(WorkbenchPreferenceDialog.java:211)
	at org.eclipse.ui.internal.OpenPreferencesAction.run(OpenPreferencesAction.java:63)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

!ENTRY org.python.pydev.shared_core 1 1 2017-08-08 14:24:01.612
!MESSAGE Restoring info for: C:\Python27\python.exe
!STACK 0
java.lang.RuntimeException: Restoring info for: C:\Python27\python.exe
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:529)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.internalRecreateCacheGetInterpreterInfos(AbstractInterpreterManager.java:345)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:655)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$5.run(AbstractInterpreterPreferencesPage.java:282)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
Caused by: java.io.IOException: Expecting: C:\ncs03\python_work\.metadata\.plugins\org.python.pydev\v1_258tvcdekrk5tmtf5h0ez044z\modulesKeys to exist (and be a file).
	at org.python.pydev.editor.codecompletion.revisited.ModulesManager.loadFromFile(ModulesManager.java:293)
	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.load(SystemModulesManager.java:397)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:527)
	... 4 more

!ENTRY org.python.pydev.shared_core 1 1 2017-08-08 14:24:01.779
!MESSAGE Finished restoring information for: C:\Python27\python.exe at: C:\ncs03\python_work\.metadata\.plugins\org.python.pydev\v1_258tvcdekrk5tmtf5h0ez044z
!STACK 0
java.lang.RuntimeException: Finished restoring information for: C:\Python27\python.exe at: C:\ncs03\python_work\.metadata\.plugins\org.python.pydev\v1_258tvcdekrk5tmtf5h0ez044z
	at org.python.pydev.core.log.Log.logInfo(Log.java:66)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.getInterpretersFromPersistedString(AbstractInterpreterManager.java:574)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.internalRecreateCacheGetInterpreterInfos(AbstractInterpreterManager.java:345)
	at org.python.pydev.ui.interpreters.AbstractInterpreterManager.setInfos(AbstractInterpreterManager.java:655)
	at org.python.pydev.ui.pythonpathconf.AbstractInterpreterPreferencesPage$5.run(AbstractInterpreterPreferencesPage.java:282)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

!ENTRY org.python.pydev.shared_core 4 4 2017-08-08 14:24:01.931
!MESSAGE Info: Rebuilding internal caches: C:\ncs03\python_work\.metadata\.plugins\com.python.pydev.analysis\python_v1_258tvcdekrk5tmtf5h0ez044z\python.pydevsysteminfo (Expected error to be provided and got no error!)

!ENTRY org.python.pydev.shared_core 4 4 2017-08-08 14:24:19.853
!MESSAGE Info: Rebuilding internal caches: C:\ncs03\python_work\.metadata\.plugins\org.eclipse.core.resources\.projects\Hello\com.python.pydev.analysis\AdditionalProjectInterpreterInfo.pydevinfo (Expected error to be provided and got no error!)

!ENTRY org.eclipse.jface 2 0 2017-08-08 14:24:57.309
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2017-08-08 14:24:57.309
!MESSAGE A conflict occurred for CTRL+D:
Binding(CTRL+D,
	ParameterizedCommand(Command(org.eclipse.ui.edit.text.delete.line,Delete Line,
		Delete a line of text,
		Category(org.eclipse.ui.category.textEditor,Text Editing,Text Editing Commands,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@589c341d,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)
Binding(CTRL+D,
	ParameterizedCommand(Command(io.emmet.eclipse.commands.match_pair_outward,Match Pair Outward,
		,
		Category(io.emmet.eclipse.commands.category,Emmet,null,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@7fce4c0b,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.ui.textEditorScope,,,system)

!ENTRY org.eclipse.ui 4 4 2017-08-08 14:25:01.982
!MESSAGE Conflicting handlers for org.python.pydev.editor.actions.execLineInConsole: {ActionHandler(org.python.proxies.__main__$ExecuteLine$11@3a2d8866)} vs {ActionHandler(org.python.proxies.__main__$ExecuteLine$9@df9ca27)}

!ENTRY org.eclipse.ui 4 4 2017-08-08 14:25:01.983
!MESSAGE Conflicting handlers for org.python.pydev.editor.actions.execLineInConsole: {ActionHandler(org.python.proxies.__main__$ExecuteLine$11@3a2d8866)} vs {ActionHandler(org.python.proxies.__main__$ExecuteLine$9@df9ca27)}

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:25:17.003
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.number'

!ENTRY org.eclipse.jface.text 2 0 2017-08-08 14:25:17.003
!MESSAGE Duplicate template id: 'org.eclipse.wst.xslt.templates.xpath.round'

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 14:33:18.227
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 14:33:18.278
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 14:48:45.335
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 14:48:45.335
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 14:54:35.743
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 14:54:35.743
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 15:05:55.239
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 15:05:55.239
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 15:39:13.949
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 15:39:13.949
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 15:58:22.992
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 15:58:23.008
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 16:07:18.493
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 16:07:18.493
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 16:36:48.901
!MESSAGE Non IFiles not supported yet

!ENTRY org.eclipse.lsp4e 1 0 2017-08-08 16:36:48.902
!MESSAGE Non IFiles not supported yet

!ENTRY org.python.pydev.shared_core 1 1 2017-08-08 16:39:14.773
!MESSAGE No existing console history at: C:\ncs03\python_work\.metadata\.plugins\org.python.pydev.shared_interactive_console\history.py
!STACK 0
java.io.FileNotFoundException: C:\ncs03\python_work\.metadata\.plugins\org.python.pydev.shared_interactive_console\history.py (지정된 파일을 찾을 수 없습니다)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at java.io.FileReader.<init>(Unknown Source)
	at org.python.pydev.shared_interactive_console.console.ScriptConsoleGlobalHistory.load(ScriptConsoleGlobalHistory.java:96)
	at org.python.pydev.shared_interactive_console.console.ScriptConsoleGlobalHistory.<init>(ScriptConsoleGlobalHistory.java:45)
	at org.python.pydev.shared_interactive_console.console.ScriptConsoleGlobalHistory.<clinit>(ScriptConsoleGlobalHistory.java:37)
	at org.python.pydev.shared_interactive_console.console.ScriptConsoleHistory.<init>(ScriptConsoleHistory.java:56)
	at org.python.pydev.shared_interactive_console.console.ui.ScriptConsole.<init>(ScriptConsole.java:204)
	at org.python.pydev.debug.newconsole.PydevConsole.<init>(PydevConsole.java:84)
	at org.python.pydev.debug.newconsole.PydevDebugConsole.<init>(PydevDebugConsole.java:29)
	at org.python.pydev.debug.newconsole.PydevConsoleFactory.createDebugConsole(PydevConsoleFactory.java:284)
	at org.python.pydev.debug.newconsole.PydevConsoleFactory.createDebugConsole(PydevConsoleFactory.java:259)
	at org.python.pydev.debug.console.PromptOverlay.<init>(PromptOverlay.java:77)
	at org.python.pydev.debug.console.PromptOverlayConsolePageParticipant.init(PromptOverlayConsolePageParticipant.java:48)
	at org.eclipse.ui.internal.console.ConsoleView$3.run(ConsoleView.java:326)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.console.ConsoleView.doCreatePage(ConsoleView.java:323)
	at org.eclipse.ui.part.PageBookView.createPage(PageBookView.java:400)
	at org.eclipse.ui.part.PageBookView.partActivated(PageBookView.java:743)
	at org.eclipse.ui.internal.console.ConsoleView$4.run(ConsoleView.java:395)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4211)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3827)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

!ENTRY org.eclipse.jface 2 0 2017-08-08 16:41:10.491
!MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
!SUBENTRY 1 org.eclipse.jface 2 0 2017-08-08 16:41:10.491
!MESSAGE A conflict occurred for CTRL+SHIFT+3:
Binding(CTRL+SHIFT+3,
	ParameterizedCommand(Command(org.eclipse.wst.jsdt.debug.ui.script.opensource,Open Source,
		Shows the JavaScript source for the selected script element,
		Category(org.eclipse.wst.jsdt.debug.ui.category,JavaScript Debug,Tooling for debugging JavaScript,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@1fabd232,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.eclipse.debug.ui.debugging,,,system)
Binding(CTRL+SHIFT+3,
	ParameterizedCommand(Command(org.python.pydev.editor.actions.uncomment,Python Uncomment,
		Uncomments a python line (Removes # from the beggining of the line),
		Category(org.python.pydev.ui.category.source,PyDev - Editor,PyDev editor category,true),
		org.eclipse.ui.internal.WorkbenchHandlerServiceHandler@10d69e2d,
		,,true),null),
	org.eclipse.ui.defaultAcceleratorConfiguration,
	org.python.pydev.ui.editor.scope,,,system)

!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:51:18.045
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:51:18.046
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:51:18.143
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:51:18.143
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:51:19.542
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:51:19.542
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:51:19.641
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:51:19.641
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:51:21.540
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:51:21.540
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:51:21.641
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:51:21.641
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:55:09.355
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:55:09.355
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:55:09.454
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:55:09.454
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:55:12.853
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:55:12.853
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:55:12.952
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:55:12.952
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:55:16.552
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:55:16.552
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:55:16.653
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:55:16.653
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:55:45.855
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:55:45.855
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 16:55:45.956
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 16:55:45.956
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:13:03.003
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:13:03.003
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:13:03.102
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:13:03.102
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:13:04.802
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:13:04.802
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:13:04.901
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:13:04.901
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:13:07.600
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:13:07.600
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:13:07.699
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:13:07.700
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:13:08.998
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:13:08.998
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:13:09.097
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:13:09.097
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:13:59.593
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:13:59.593
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:13:59.693
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:13:59.693
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)


!ENTRY org.eclipse.ui 4 0 2017-08-08 17:14:15.107
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException
	at org.python.pydev.debug.console.SetLayoutAction.run(SetLayoutAction.java:72)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4418)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4236)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3824)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:15:37.608
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:15:37.608
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:15:37.707
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:15:37.707
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:16:32.799
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:16:32.800
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 17:16:32.898
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 17:16:32.898
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 18:16:34.567
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 18:16:34.568
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 18:16:34.666
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 18:16:34.667
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 18:22:18.802
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 18:22:18.802
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)


!ENTRY org.python.pydev.debug 4 4 2017-08-08 18:22:18.901
!MESSAGE Error fetching a variable
!STACK 1
org.eclipse.core.runtime.CoreException: pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

	at org.python.pydev.debug.model.remote.EvaluateExpressionCommand.getResponse(EvaluateExpressionCommand.java:76)
	at org.python.pydev.debug.model.PyWatchExpressionDelegate.commandComplete(PyWatchExpressionDelegate.java:123)
	at org.python.pydev.debug.model.remote.AbstractDebuggerCommand.processResponse(AbstractDebuggerCommand.java:151)
	at org.python.pydev.debug.model.remote.DebuggerReader.processCommand(DebuggerReader.java:118)
	at org.python.pydev.debug.model.remote.DebuggerReader.run(DebuggerReader.java:141)
	at java.lang.Thread.run(Unknown Source)
!SUBENTRY 1 org.python.pydev.debug 4 4 2017-08-08 18:22:18.901
!MESSAGE pydevd error:Error evaluating expression Traceback (most recent call last):
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_comm.py", line 1118, in do_it
    result = pydevd_vars.evaluate_expression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\ncs03\eclipse\plugins\org.python.pydev_5.8.0.201706061859\pysrc\_pydevd_bundle\pydevd_vars.py", line 337, in evaluate_expression
    expression = str(expression.replace('@LINE@', '\n'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

